// Generated by tools/make_clock_font.py (Helvetica 9px) - do not edit
#pragma once
#include <Adafruit_GFX.h>

static uint8_t ClockBitmaps[] = {
  6,9,9,9,9,9,6,0,1,3,1,1,
  1,1,1,0,6,9,1,2,4,8,15,0,
  6,9,1,6,1,9,6,0,2,6,6,10,
  15,2,2,0,7,0,6,1,1,1,6,0,
  6,9,14,9,9,9,6,0,15,1,2,2,
  4,4,4,0,6,9,9,6,9,9,6,0,
  6,9,9,9,7,9,6,0,1,0,0,0,
  0,1,
};

static GFXglyph ClockGlyphs[] = {
  {0, 4, 7, 5, 0, -7},
  {8, 2, 7, 5, 1, -7},
  {16, 4, 7, 5, 0, -7},
  {24, 4, 7, 5, 0, -7},
  {32, 4, 7, 5, 0, -7},
  {40, 3, 7, 5, 0, -7},
  {48, 4, 7, 5, 0, -7},
  {56, 4, 7, 5, 0, -7},
  {64, 4, 7, 5, 0, -7},
  {72, 4, 7, 5, 0, -7},
  {80, 1, 6, 5, 1, -6},
};

static const GFXfont ClockFont = {ClockBitmaps, ClockGlyphs, '0', ':', 9};
