#!/usr/bin/env python3
"""Generate a tiny clock font (digits + colon) matching the home header's
Helvetica 9px line, in Adafruit GFX bitmap font format."""
from PIL import Image, ImageDraw, ImageFont

SANS = ("Helvetica.ttc", "HelveticaNeue.ttc", "Helvetica.ttf", "Arial.ttf")
fnt = None
for n in SANS:
    for p in [f"/System/Library/Fonts/{n}", f"/System/Library/Fonts/Supplemental/{n}"]:
        try:
            fnt = ImageFont.truetype(p, 9)
            break
        except Exception:
            pass
    if fnt:
        break
assert fnt, "no helvetica found"

chars = "0123456789:"
bitmaps = bytearray()
glyphs = []
adv = int(fnt.getlength("0"))
for c in chars:
    img = Image.new("1", (64, 64), 0)
    ImageDraw.Draw(img).text((0, 0), c, font=fnt, fill=1)
    bbox = img.getbbox()
    if not bbox:
        glyphs.append((0, 0, 0, adv, 0, 0))
        continue
    x0, y0, x1, y1 = bbox
    w, h = x1 - x0, y1 - y0
    off = len(bitmaps)
    for y in range(y0, y1):
        byte = 0
        for x in range(x0, x1):
            byte = (byte << 1) | (1 if img.getpixel((x, y)) else 0)
        bitmaps.append(byte)
    while len(bitmaps) % 2:
        bitmaps.append(0)
    glyphs.append((off, w, h, adv, x0, -h))

out = []
out.append("// Generated by tools/make_clock_font.py (Helvetica 9px) - do not edit")
out.append("#pragma once")
out.append('#include <Adafruit_GFX.h>')
out.append("")
out.append("static const uint8_t ClockBitmaps[] = {")
for i in range(0, len(bitmaps), 12):
    out.append("  " + ",".join(str(b) for b in bitmaps[i:i+12]) + ",")
out.append("};")
out.append("")
out.append("static const GFXglyph ClockGlyphs[] = {")
for g in glyphs:
    out.append("  {%d, %d, %d, %d, %d, %d}," % g)
out.append("};")
out.append("")
out.append("static const GFXfont ClockFont = {ClockBitmaps, ClockGlyphs, '0', ':', 9};")
open("firmware/src/clock_font.h", "w").write("\n".join(out) + "\n")
print("clock_font.h:", len("\n".join(out)), "bytes,", len(glyphs), "glyphs")
